Added Comments & intro/conclusion
jni/mpl-volume-viewer pull request #1
Opened 2017-03-24 15:53 UTC by Kacawi

- Added some documentation to the code chunks
- Added a begin and end to the tutorial with editorial note

2017-03-24 22:51 UTC, jni requested changes
Hi @Kacawi! I've left a few comments. Let me know what you think and if you can, please update the PR! Thanks!

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "This tutorial will show you how to import and display image data, and how you can make a fully functional slice viewer to view all the slices in our MRI volume without any interference.\n",
This is now quite repetitive ("today's tutorial will show you...", "this tutorial will show you..."). I'm also not a fan of using the standard matplotlib spiel to introduce it — it seems out of place to talk about plots in this context. Now that I see what you're going for, how about the following:

> Most of you are familiar with image data, taken with ordinary cameras (these are often called "natural images" in the scientific literature), but also with specialized instruments, such as microscopes or telescopes. When working with images in Python, the most common way to display them is using the `imshow` function of *Matplotlib*, Python's most popular plotting library.

> In this tutorial, we'll show you how to extend this function to display *3D volumetric data*, which you can think of as a stack of images. Together, they describe a 3D structure. For example, magnetic resonance imaging (MRI) and computed tomography (CT) scans measure the 3D structure inside the human body; X-ray microtomography measures the 3D structure inside materials such as glass, or metal alloys; and light-sheet microscopes measure fluorescent particles inside biological tissues. We'll demonstrate how to download an MRI dataset and display the slices using matplotlib. But first, let's go over some basics: how to display images with Matplotlib's `imshow`:

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# import data module \n",
I would remove all comments about imports, as they almost repeat the line underneath them verbatim.

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Gather some data \n",
This one is better, but I would rather place it in the markdown cell above it, as follows:

"""
Now we can import matplotlib and display some data. We'll load some example data that is included in the `data` module of the *scikit-image* library:
"""

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Show subplot images and set titles \n",
These are good. =) Maybe reword as: "show an image in each subplot"

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Initialize the subplots\n",
"Initialize three subplot panels side by side"

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Import\n",
Again, this particular type of comment, I think, adds nothing.

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Extract the contents\n",
Extract the contents into the temporary directory we created earlier

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Get a NumPy array\n",
How about: Get a plain numpy array, without all the metadata

(but maybe that just makes it more complicated, I'm not sure)

2017-03-24 22:51 UTC, jni commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# Go to the next slice\n",
In this case (next to a def), I would prefer it as a function docstring:

```python
def next_slice(ax):
    """Go to the next slice."""
```

2017-03-27 08:29 UTC, Kacawi commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "This tutorial will show you how to import and display image data, and how you can make a fully functional slice viewer to view all the slices in our MRI volume without any interference.\n",
@jni I understand. I agree with your proposal!

2017-03-27 08:29 UTC, Kacawi commented on notebooks/Viewing 3D volumetric data with matplotlib.ipynb
> +    "# import data module \n",
True. I'll remove them.

2017-03-27 08:42 UTC, Kacawi commented
@jni Thanks for the feedback! I made some changes in accordance with your feedback. Could you please review?

2017-03-27 15:11 UTC, jni commented
Hi Karlijn! Annoyingly, github can't render the diff (looks like we've hit that limitation of using notebooks that we were worried about), but I went through it and have the following comments:

- it looks like `import matplotlib.pyplot as plt` is gone now! Specifically, this little section has some issues:

<img width="954" alt="screen shot 2017-03-27 at 11 07 16 am" src="https://cloud.githubusercontent.com/assets/492549/24363358/a1452d40-12dd-11e7-9c2f-144a06996b47.png">

- the `urlretrieve` bit is a bit mangled also:

<img width="796" alt="screen shot 2017-03-27 at 11 08 30 am" src="https://cloud.githubusercontent.com/assets/492549/24363407/c6e6132a-12dd-11e7-85f3-2162d28e3912.png">

That's it! I like your new conclusion, it really wraps it up much more nicely than I had it. =) If you want, I can merge and fix those things myself, let me know.

2017-04-10 14:05 UTC, Kacawi commented
@jni I pushed some commits that should hopefully take care of the things you mention! Could you review if it's OK now?

2017-04-11 13:45 UTC, merged

2017-04-11 13:47 UTC, jni commented
@Kacawi Github was still annoying but it helped actually, because I decided to just download your changes, make a couple of tweaks, and then merge directly in the command line. =)

The resulting notebook: https://github.com/jni/mpl-volume-viewer/blob/master/notebooks/Viewing%203D%20volumetric%20data%20with%20matplotlib.ipynb

2017-04-11 13:48 UTC, jni commented
btw, for future reference, it's usually preferable to submit PRs from a different branch. =)