fix signature of toggle_overlay called by keymap
jni/mpl-volume-viewer pull request #10
Opened 2021-04-20 17:12 UTC by ferdymercury

to prevent crash TypeError: _toggle_overlay() missing 1 required positional argument: 'ax'

2021-04-21 04:17 UTC, jni approved these changes

2021-04-21 04:19 UTC, jni requested changes
Actually, does this work? It's matplotlib processing the events, and I expect it passes the event, figure, and axes to the callback — see where the callbacks are set lower in the code. I think what you need is simply to add `if ax is not None and ax.overlay is not None:`?

2021-04-21 07:04 UTC, ferdymercury commented
But you use:
```

KEYMAP = {
    'down': _dscroll,
    'up': _dscroll,
    'j': _dscroll,
    'k': _dscroll,
    'f': _toggle_overlay,
}
if event.key in KEYMAP:
            f = KEYMAP[event.key]
            f(event, self)
```

So you always call the function _toggle_overlay with event as single argument, not?

2021-04-22 03:33 UTC, jni commented
You are right! :facepalm: However the overlay functionality appears to be completely broken. If I add an overlay with `labels=`, then neither f nor any other shortcut works at all. Here's an example script (requires `pip install scikit-image[data]>=0.18`):

```python
import numpy as np
import mpl_volume_viewer as vv
from skimage import data
from scipy import ndimage as ndi
import matplotlib.pyplot as plt


nuclei = data.cells3d()[:, 1]
labels, _ = ndi.label(nuclei > np.mean(nuclei))

viewer = vv.SliceViewer(
        nuclei,
        labels=labels,
        )

plt.show()
```

This doesn't work either with or without this PR.

2021-04-22 08:44 UTC, ferdymercury commented
> You are right! facepalm However the overlay functionality appears to be completely broken. If I add an overlay with `labels=`, then neither f nor any other shortcut works at all. Here's an example script (requires `pip install scikit-image[data]>=0.18`):
> 
> ```python
> import numpy as np
> import mpl_volume_viewer as vv
> from skimage import data
> from scipy import ndimage as ndi
> import matplotlib.pyplot as plt
> 
> 
> nuclei = data.cells3d()[:, 1]
> labels, _ = ndi.label(nuclei > np.mean(nuclei))
> 
> viewer = vv.SliceViewer(
>         nuclei,
>         labels=labels,
>         )
> 
> plt.show()
> ```
> 
> This doesn't work either with or without this PR.

It should be fixed now.

2021-04-22 09:06 UTC, jni commented
It doesn't crash now, which is :+1:! But do you see anything when pressing f? I don't? At any rate I'm happy to merge as it's already an improvement, I just want to check whether the problem is only on my end.

Thanks for all the fixes btw, this is awesome!!! :blush:

2021-04-22 09:13 UTC, ferdymercury commented
You are welcome ;)

Using Spyder3 and the 'merged' version with master, I see:

![image](https://user-images.githubusercontent.com/10653970/115688735-69dcd980-a329-11eb-9fc6-29c2e9fb8142.png)

![image](https://user-images.githubusercontent.com/10653970/115688781-73fed800-a329-11eb-886a-2c9f692b4dde.png)

2021-04-22 10:01 UTC, jni approved these changes

2021-04-22 10:02 UTC, merged